export const postActionTypes = {
  GET_POSTS_BY_USER_REQUEST: 'GET_POSTS_BY_USER_REQUEST',
  GET_POSTS_BY_USER_SUCCESS: 'GET_POSTS_BY_USER_SUCCESS',
  GET_POSTS_BY_USER_FAIL: 'GET_POSTS_BY_USER_FAIL',
  GRAB_POST_CITY: 'GRAB_POST_CITY',
  GRAB_POST_CATAGORY: 'GRAB_POST_CATAGORY',
  GRAB_FORM_DATA: 'GRAB_FORM_DATA',
  CREATE_NEW_POST_REQUEST: 'CREATE_NEW_POST_REQUEST',
  CREATE_NEW_POST_SUCCESS: 'CREATE_NEW_POST_SUCCESS',
  CREATE_NEW_POST_FAIL: 'CREATE_NEW_POST_FAIL',
  DISTROY_DATA: 'DISTROY_DATA',
  SET_EDIT: 'SET_EDIT',
}
