const authActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',
  REQUEST_USER: 'REQUEST_USER',
  REQUEST_USER_SUCCESS: 'REQUEST_USER_SUCCESS',
  REQUEST_USER_FAIL: 'REQUEST_USER_FAIL',
  CLEAR_ERROR: 'CLEAR_ERROR',
  LOGOUT: 'LOGOUT',
}

export default authActionTypes
